/*
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verbose -warn-error +9 -drop WasmSupport -drop C_Endianness -drop C -tmpdir ../out -fsopt --cache_dir -fsopt ../out -no-prefix Main -no-prefix Utils -no-prefix Const -no-prefix Common -no-prefix Publish -no-prefix Connect -no-prefix Disconnect -no-prefix FFI -no-prefix Debug -no-prefix Debug_FFI -o ../mqttPacketParser.out main.fst common.fst const.fst publish.fst connect.fst disconnect.fst ffi.fst debug.fst debug_ffi.fst ffi.c debug_ffi.c callMain.c
  F* version: ad3db6d3
  KreMLin version: 2f843633
 */

#include "kremlib.h"
#ifndef __Debug_FFI_H
#define __Debug_FFI_H




extern void print_hex_u8(uint8_t i);

extern void print_hex_u16(uint16_t i);

extern void print_buffer_u8(uint8_t *buffer, uint32_t buffer_size);

extern void print_buffer_u16(uint16_t *buffer, uint32_t buffer_size);

#define __Debug_FFI_H_DEFINED
#endif