/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verbose -warn-error +9 -drop WasmSupport -drop C_Endianness -drop C -tmpdir ../out -fsopt --cache_dir -fsopt ../out -no-prefix Main -no-prefix Utils -no-prefix Const -no-prefix Common -no-prefix Publish -no-prefix Connect -no-prefix Disconnect -no-prefix FFI -no-prefix Debug -no-prefix Debug_FFI -o ../mqttPacketParser.out main.fst common.fst const.fst publish.fst connect.fst disconnect.fst ffi.fst debug.fst debug_ffi.fst ffi.c debug_ffi.c callMain.c
  F* version: ad3db6d3
  KreMLin version: 2f843633
 */

#include "kremlib.h"
#ifndef __Disconnect_H
#define __Disconnect_H

#include "Const.h"
#include "Common.h"


struct_fixed_header assemble_disconnect_struct(struct_disconnect_parts s);

struct_disconnect_reason get_disconnect_reason(uint8_t reason_code);

struct_disconnect_packet_seed
disconnect_packet_parser(uint8_t *packet_data, uint32_t packet_size, uint32_t next_start_index);

struct_fixed_header disconnect_packet_parse_result(struct_share_common_data share_common_data);

#define __Disconnect_H_DEFINED
#endif
