/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verbose -warn-error +9 -drop WasmSupport -drop C_Endianness -drop C -tmpdir ../out -fsopt --cache_dir -fsopt ../out -no-prefix Main -no-prefix Utils -no-prefix Const -no-prefix Common -no-prefix Publish -no-prefix Connect -no-prefix Disconnect -no-prefix FFI -no-prefix Debug -no-prefix Debug_FFI -o ../mqttPacketParser.out main.fst common.fst const.fst publish.fst connect.fst disconnect.fst ffi.fst debug.fst debug_ffi.fst ffi.c debug_ffi.c callMain.c
  F* version: ad3db6d3
  KreMLin version: 2f843633
 */

#include "Const.h"

uint8_t max_u8 = (uint8_t)255U;

uint16_t max_u16 = (uint16_t)65535U;

uint32_t max_u32 = (uint32_t)4294967295U;

uint32_t min_packet_size = (uint32_t)2U;

uint32_t max_packet_size = (uint32_t)268435460U;

uint32_t max_request_size = (uint32_t)268435461U;

uint32_t min_request_size = (uint32_t)0U;

uint32_t max_payload_size = (uint32_t)268435455U;

uint8_t define_mqtt_control_packet_CONNECT = (uint8_t)1U;

uint8_t define_mqtt_control_packet_CONNACK = (uint8_t)2U;

uint8_t define_mqtt_control_packet_PUBLISH = (uint8_t)3U;

uint8_t define_mqtt_control_packet_PUBACK = (uint8_t)4U;

uint8_t define_mqtt_control_packet_PUBREC = (uint8_t)5U;

uint8_t define_mqtt_control_packet_PUBREL = (uint8_t)6U;

uint8_t define_mqtt_control_packet_PUBCOMP = (uint8_t)7U;

uint8_t define_mqtt_control_packet_SUBSCRIBE = (uint8_t)8U;

uint8_t define_mqtt_control_packet_SUBACK = (uint8_t)9U;

uint8_t define_mqtt_control_packet_UNSUBSCRIBE = (uint8_t)10U;

uint8_t define_mqtt_control_packet_UNSUBACK = (uint8_t)11U;

uint8_t define_mqtt_control_packet_PINGREQ = (uint8_t)12U;

uint8_t define_mqtt_control_packet_PINGRESP = (uint8_t)13U;

uint8_t define_mqtt_control_packet_DISCONNECT = (uint8_t)14U;

uint8_t define_mqtt_control_packet_AUTH = (uint8_t)15U;

C_String_t define_mqtt_control_packet_CONNECT_label = "CONNECT";

C_String_t define_mqtt_control_packet_CONNACK_label = "CONNACK";

C_String_t define_mqtt_control_packet_PUBLISH_label = "PUBLISH";

C_String_t define_mqtt_control_packet_PUBACK_label = "PUBACK";

C_String_t define_mqtt_control_packet_PUBREC_label = "PUBREC";

C_String_t define_mqtt_control_packet_PUBREL_label = "PUBREL";

C_String_t define_mqtt_control_packet_PUBCOMP_label = "PUBCOMP";

C_String_t define_mqtt_control_packet_SUBSCRIBE_label = "SUBSCRIBE";

C_String_t define_mqtt_control_packet_SUBACK_label = "SUBACK";

C_String_t define_mqtt_control_packet_UNSUBSCRIBE_label = "UNSUBSCRIBE";

C_String_t define_mqtt_control_packet_UNSUBACK_label = "UNSUBACK";

C_String_t define_mqtt_control_packet_PINGREQ_label = "PINGREQ";

C_String_t define_mqtt_control_packet_PINGRESP_label = "PINGRESP";

C_String_t define_mqtt_control_packet_DISCONNECT_label = "DISCONNECT";

C_String_t define_mqtt_control_packet_AUTH_label = "AUTH";

uint8_t define_dup_flag_first_delivery = (uint8_t)0U;

uint8_t define_dup_flag_re_delivery = (uint8_t)1U;

uint8_t define_qos_flag_at_most_once_delivery = (uint8_t)0b00U;

uint8_t define_qos_flag_at_least_once_delivery = (uint8_t)0b01U;

uint8_t define_qos_flag_exactly_once_delivery = (uint8_t)0b10U;

uint8_t define_retain_flag_must_not_store_application_message = (uint8_t)0U;

uint8_t define_retain_flag_must_store_application_message = (uint8_t)1U;

uint8_t define_flag_CONNECT = (uint8_t)0b0000U;

uint8_t define_flag_CONNACK = (uint8_t)0b0000U;

uint8_t define_flag_PUBACK = (uint8_t)0b0000U;

uint8_t define_flag_PUBREC = (uint8_t)0b0000U;

uint8_t define_flag_PUBREL = (uint8_t)0b0010U;

uint8_t define_flag_PUBCOMP = (uint8_t)0b0000U;

uint8_t define_flag_SUBSCRIBE = (uint8_t)0b0010U;

uint8_t define_flag_SUBACK = (uint8_t)0b0000U;

uint8_t define_flag_UNSUBSCRIBE = (uint8_t)0b0010U;

uint8_t define_flag_UNSUBACK = (uint8_t)0b0000U;

uint8_t define_flag_PINGREQ = (uint8_t)0b0000U;

uint8_t define_flag_PINGRESP = (uint8_t)0b0000U;

uint8_t define_flag_DISCONNECT = (uint8_t)0b0000U;

uint8_t define_flag_AUTH = (uint8_t)0b0000U;

uint8_t __proj__Mkstruct_flags__item__flag(struct_flags projectee)
{
  return projectee.flag;
}

uint8_t __proj__Mkstruct_flags__item__dup_flag(struct_flags projectee)
{
  return projectee.dup_flag;
}

uint8_t __proj__Mkstruct_flags__item__qos_flag(struct_flags projectee)
{
  return projectee.qos_flag;
}

uint8_t __proj__Mkstruct_flags__item__retain_flag(struct_flags projectee)
{
  return projectee.retain_flag;
}

uint8_t
__proj__Mkstruct_fixed_header_constant__item__message_type_constant(
  struct_fixed_header_constant projectee
)
{
  return projectee.message_type_constant;
}

C_String_t
__proj__Mkstruct_fixed_header_constant__item__message_name_constant(
  struct_fixed_header_constant projectee
)
{
  return projectee.message_name_constant;
}

struct_flags
__proj__Mkstruct_fixed_header_constant__item__flags_constant(
  struct_fixed_header_constant projectee
)
{
  return projectee.flags_constant;
}

uint8_t __proj__Mkstruct_connect_flags__item__connect_flag(struct_connect_flags projectee)
{
  return projectee.connect_flag;
}

uint8_t __proj__Mkstruct_connect_flags__item__user_name(struct_connect_flags projectee)
{
  return projectee.user_name;
}

uint8_t __proj__Mkstruct_connect_flags__item__password(struct_connect_flags projectee)
{
  return projectee.password;
}

uint8_t __proj__Mkstruct_connect_flags__item__will_retain(struct_connect_flags projectee)
{
  return projectee.will_retain;
}

uint8_t __proj__Mkstruct_connect_flags__item__will_qos(struct_connect_flags projectee)
{
  return projectee.will_qos;
}

uint8_t __proj__Mkstruct_connect_flags__item__will_flag(struct_connect_flags projectee)
{
  return projectee.will_flag;
}

uint8_t __proj__Mkstruct_connect_flags__item__clean_start(struct_connect_flags projectee)
{
  return projectee.clean_start;
}

uint8_t
__proj__Mkstruct_connect_property__item__connect_property_id(struct_connect_property projectee)
{
  return projectee.connect_property_id;
}

C_String_t
__proj__Mkstruct_connect_property__item__connect_property_name(
  struct_connect_property projectee
)
{
  return projectee.connect_property_name;
}

uint8_t define_connect_property_session_expiry_interval_id = (uint8_t)0x11U;

uint8_t define_connect_property_receive_maximum_id = (uint8_t)0x21U;

uint8_t define_connect_property_maximum_packet_size_id = (uint8_t)0x27U;

uint8_t define_connect_property_topic_alias_maximum_id = (uint8_t)0x22U;

uint8_t define_connect_property_request_response_information_id = (uint8_t)0x19U;

uint8_t define_connect_property_request_problem_information_id = (uint8_t)0x17U;

uint8_t define_connect_property_user_property_id = (uint8_t)0x26U;

uint8_t define_connect_property_authentication_method_id = (uint8_t)0x15U;

uint8_t define_connect_property_authentication_data_id = (uint8_t)0x16U;

struct_connect_property define_struct_connect_property_session_expiry_interval;

struct_connect_property define_struct_connect_property_receive_maximum;

struct_connect_property define_struct_connect_property_maximum_packet_size;

struct_connect_property define_struct_connect_property_topic_alias_maximum;

struct_connect_property define_struct_connect_property_request_response_information;

struct_connect_property define_struct_connect_property_request_problem_information;

struct_connect_property define_struct_connect_property_user_property;

struct_connect_property define_struct_connect_property_authentication_method;

struct_connect_property define_struct_connect_property_authentication_data;

uint16_t __proj__Mkstruct_utf8_string__item__utf8_string_length(struct_utf8_string projectee)
{
  return projectee.utf8_string_length;
}

uint8_t *__proj__Mkstruct_utf8_string__item__utf8_string_value(struct_utf8_string projectee)
{
  return projectee.utf8_string_value;
}

uint8_t
__proj__Mkstruct_utf8_string__item__utf8_string_status_code(struct_utf8_string projectee)
{
  return projectee.utf8_string_status_code;
}

uint32_t
__proj__Mkstruct_utf8_string__item__utf8_next_start_index(struct_utf8_string projectee)
{
  return projectee.utf8_next_start_index;
}

uint8_t define_disconnect_reason_code_normal_disconnection = (uint8_t)0U;

uint8_t define_disconnect_reason_code_disconnect_with_will_message = (uint8_t)4U;

uint8_t define_disconnect_reason_code_unspecified_error = (uint8_t)128U;

uint8_t define_disconnect_reason_code_malformed_packet = (uint8_t)129U;

uint8_t define_disconnect_reason_code_protocol_error = (uint8_t)130U;

uint8_t define_disconnect_reason_code_implementation_specific_error = (uint8_t)131U;

uint8_t define_disconnect_reason_code_not_authorized = (uint8_t)135U;

uint8_t define_disconnect_reason_code_server_busy = (uint8_t)137U;

uint8_t define_disconnect_reason_code_server_shutting_down = (uint8_t)139U;

uint8_t define_disconnect_reason_code_keep_alive_timeout = (uint8_t)141U;

uint8_t define_disconnect_reason_code_session_taken_over = (uint8_t)142U;

uint8_t define_disconnect_reason_code_topic_filter_invalid = (uint8_t)143U;

uint8_t define_disconnect_reason_code_topic_name_invalid = (uint8_t)144U;

uint8_t define_disconnect_reason_receive_maximum_exceeded = (uint8_t)147U;

uint8_t define_disconnect_reason_topic_alias_invalid = (uint8_t)148U;

uint8_t define_disconnect_reason_packet_too_large = (uint8_t)149U;

uint8_t define_disconnect_reason_message_rate_too_high = (uint8_t)150U;

uint8_t define_disconnect_reason_quota_exceeded = (uint8_t)151U;

uint8_t define_disconnect_reason_administrative_action = (uint8_t)152U;

uint8_t define_disconnect_reason_payload_format_invalid = (uint8_t)153U;

uint8_t define_disconnect_reason_retain_not_supported = (uint8_t)154U;

uint8_t define_disconnect_reason_qos_not_supported = (uint8_t)155U;

uint8_t define_disconnect_reason_use_another_server = (uint8_t)156U;

uint8_t define_disconnect_reason_server_moved = (uint8_t)157U;

uint8_t define_disconnect_reason_shared_subscriptions_not_supported = (uint8_t)158U;

uint8_t define_disconnect_reason_connection_rate_exceeded = (uint8_t)159U;

uint8_t define_disconnect_reason_maximum_connect_time = (uint8_t)160U;

uint8_t define_disconnect_reason_subscription_identifiers_not_supported = (uint8_t)161U;

uint8_t define_disconnect_reason_wildcard_subscriptions_not_supported = (uint8_t)162U;

C_String_t define_disconnect_reason_code_normal_disconnection_name = "Normal disconnection";

C_String_t
define_disconnect_reason_code_disconnect_with_will_message_name =
  "Disconnect with Will Message";

C_String_t define_disconnect_reason_code_unspecified_error_name = "Unspecified error";

C_String_t define_disconnect_reason_code_malformed_packet_name = "Malformed Packet";

C_String_t define_disconnect_reason_code_protocol_error_name = "Protocol Error";

C_String_t
define_disconnect_reason_code_implementation_specific_error_name =
  "Implementation specific error";

C_String_t define_disconnect_reason_code_not_authorized_name = "Not authorized";

C_String_t define_disconnect_reason_code_server_busy_name = "Server busy";

C_String_t define_disconnect_reason_code_server_shutting_down_name = "Server shutting down";

C_String_t define_disconnect_reason_code_keep_alive_timeout_name = "Keep Alive timeout";

C_String_t define_disconnect_reason_code_session_taken_over_name = "Session taken over";

C_String_t define_disconnect_reason_code_topic_filter_invalid_name = "Topic Filter invalid";

C_String_t define_disconnect_reason_code_topic_name_invalid_name = "Topic Name invalid";

C_String_t define_disconnect_reason_receive_maximum_exceeded_name = "Receive Maximum exceeded";

C_String_t define_disconnect_reason_topic_alias_invalid_name = "Topic Alias invalid";

C_String_t define_disconnect_reason_packet_too_large_name = "Packet too large";

C_String_t define_disconnect_reason_message_rate_too_high_name = "Message rate too high";

C_String_t define_disconnect_reason_quota_exceeded_name = "Quota exceeded";

C_String_t define_disconnect_reason_administrative_action_name = "Administrative action";

C_String_t define_disconnect_reason_payload_format_invalid_name = "Payload format invalid";

C_String_t define_disconnect_reason_retain_not_supported_name = "Retain not supported";

C_String_t define_disconnect_reason_qos_not_supported_name = "QoS not supported";

C_String_t define_disconnect_reason_use_another_server_name = "Use another server";

C_String_t define_disconnect_reason_server_moved_name = "Server moved";

C_String_t
define_disconnect_reason_shared_subscriptions_not_supported_name =
  "Shared Subscriptions not supported";

C_String_t define_disconnect_reason_connection_rate_exceeded_name = "Connection rate exceeded";

C_String_t define_disconnect_reason_maximum_connect_time_name = "Maximum connect time";

C_String_t
define_disconnect_reason_subscription_identifiers_not_supported_name =
  "Subscription Identifiers not supported";

C_String_t
define_disconnect_reason_wildcard_subscriptions_not_supported_name =
  "Wildcard Subscriptions not supported";

uint8_t
__proj__Mkstruct_disconnect_reason__item__disconnect_reason_code(
  struct_disconnect_reason projectee
)
{
  return projectee.disconnect_reason_code;
}

C_String_t
__proj__Mkstruct_disconnect_reason__item__disconnect_reason_code_name(
  struct_disconnect_reason projectee
)
{
  return projectee.disconnect_reason_code_name;
}

struct_disconnect_reason define_struct_disconnect_normal_disconnection;

struct_disconnect_reason define_struct_disconnect_disconnect_with_will_message;

struct_disconnect_reason define_struct_disconnect_unspecified_error;

struct_disconnect_reason define_struct_disconnect_malformed_packet;

struct_disconnect_reason define_struct_disconnect_protocol_error;

struct_disconnect_reason define_struct_disconnect_implementation_specific_error;

struct_disconnect_reason define_struct_disconnect_not_authorized;

struct_disconnect_reason define_struct_disconnect_server_busy;

struct_disconnect_reason define_struct_disconnect_server_shutting_down;

struct_disconnect_reason define_struct_disconnect_keep_alive_timeout;

struct_disconnect_reason define_struct_disconnect_session_taken_over;

struct_disconnect_reason define_struct_disconnect_topic_filter_invalid;

struct_disconnect_reason define_struct_disconnect_topic_name_invalid;

struct_disconnect_reason define_struct_disconnect_receive_maximum_exceeded;

struct_disconnect_reason define_struct_disconnect_topic_alias_invalid;

struct_disconnect_reason define_struct_disconnect_packet_too_large;

struct_disconnect_reason define_struct_disconnect_message_rate_too_high;

struct_disconnect_reason define_struct_disconnect_quota_exceeded;

struct_disconnect_reason define_struct_disconnect_administrative_action;

struct_disconnect_reason define_struct_disconnect_payload_format_invalid;

struct_disconnect_reason define_struct_disconnect_retain_not_supported;

struct_disconnect_reason define_struct_disconnect_qos_not_supported;

struct_disconnect_reason define_struct_disconnect_use_another_server;

struct_disconnect_reason define_struct_disconnect_server_moved;

struct_disconnect_reason define_struct_disconnect_shared_subscriptions_not_supported;

struct_disconnect_reason define_struct_disconnect_connection_rate_exceeded;

struct_disconnect_reason define_struct_disconnect_maximum_connect_time;

struct_disconnect_reason define_struct_disconnect_subscription_identifiers_not_supported;

struct_disconnect_reason define_struct_disconnect_wildcard_subscriptions_not_supported;

struct_disconnect_reason define_struct_disconnect_error;

uint8_t define_no_error_code = (uint8_t)0U;

uint8_t define_error_remaining_length_invalid_code = (uint8_t)1U;

uint8_t define_error_message_type_invalid_code = (uint8_t)2U;

uint8_t define_error_flag_invalid_code = (uint8_t)3U;

uint8_t define_error_dup_flag_invalid_code = (uint8_t)4U;

uint8_t define_error_qos_flag_invalid_code = (uint8_t)5U;

uint8_t define_error_retain_flag_invalid_code = (uint8_t)6U;

uint8_t define_error_topic_length_invalid_code = (uint8_t)7U;

uint8_t define_error_topic_name_dont_zero_terminated_code = (uint8_t)8U;

uint8_t define_error_property_length_invalid_code = (uint8_t)9U;

uint8_t define_error_payload_invalid_code = (uint8_t)10U;

uint8_t define_error_topic_name_have_inavlid_character_code = (uint8_t)11U;

uint8_t define_error_protocol_name_invalid_code = (uint8_t)12U;

uint8_t define_error_protocol_version_invalid_code = (uint8_t)13U;

uint8_t define_error_connect_flag_invalid_code = (uint8_t)14U;

uint8_t define_error_property_error_code = (uint8_t)15U;

uint8_t define_error_connect_id_invalid_code = (uint8_t)16U;

uint8_t define_error_disconnect_reason_invalid_code = (uint8_t)17U;

uint8_t define_error_connect_invalid_keep_alive_code = (uint8_t)18U;

C_String_t define_error_remaining_length_invalid = "remaining_length is invalid.";

C_String_t define_error_message_type_invalid = "message_type is invalid.";

C_String_t define_error_flag_invalid = "flag is invalid.";

C_String_t define_error_dup_flag_invalid = "dup_flag is invalid.";

C_String_t define_error_qos_flag_invalid = "qos_flag is invalid.";

C_String_t define_error_retain_flag_invalid = "retain_flag is invalid.";

C_String_t define_error_topic_length_invalid = "topic_length is invalid.";

C_String_t define_error_topic_name_dont_zero_terminated = "topic_name is not zero-terminated.";

C_String_t
define_error_topic_name_have_inavlid_character = "topic_name have invalid character.";

C_String_t define_error_property_length_invalid = "property_length is invalid.";

C_String_t define_error_payload_invalid = "payload is invalid.";

C_String_t define_error_protocol_name_invalid = "protocol name is invalid.";

C_String_t define_error_protocol_version_invalid = "protocol version is invalid.";

C_String_t define_error_connect_flag_invalid = "connect flag is invalid.";

C_String_t define_error_property_invalid = "property is invalid.";

C_String_t define_error_connect_id_invalid = "connect id is invalid.";

C_String_t define_error_disconnect_reason_invalid = "disconnect reason is invalid.";

C_String_t define_error_connect_keep_alive_invalid = "connect keep-alive is invalid.";

C_String_t define_no_error = "";

uint8_t __proj__Mkstruct_error_struct__item__code(struct_error_struct projectee)
{
  return projectee.code;
}

C_String_t __proj__Mkstruct_error_struct__item__message(struct_error_struct projectee)
{
  return projectee.message;
}

struct_utf8_string
__proj__Mkstruct_utf8_string_pair__item__utf8_string_pair_key(
  struct_utf8_string_pair projectee
)
{
  return projectee.utf8_string_pair_key;
}

struct_utf8_string
__proj__Mkstruct_utf8_string_pair__item__utf8_string_pair_value(
  struct_utf8_string_pair projectee
)
{
  return projectee.utf8_string_pair_value;
}

bool __proj__Mkstruct_binary_data__item__is_valid_binary_data(struct_binary_data projectee)
{
  return projectee.is_valid_binary_data;
}

uint16_t __proj__Mkstruct_binary_data__item__binary_length(struct_binary_data projectee)
{
  return projectee.binary_length;
}

uint8_t *__proj__Mkstruct_binary_data__item__binary_value(struct_binary_data projectee)
{
  return projectee.binary_value;
}

uint32_t
__proj__Mkstruct_binary_data__item__binary_next_start_index(struct_binary_data projectee)
{
  return projectee.binary_next_start_index;
}

uint8_t __proj__Mkstruct_one_byte_integer__item__one_byte_integer_value(uint8_t projectee)
{
  return projectee;
}

uint16_t __proj__Mkstruct_two_byte_integer__item__two_byte_integer_value(uint16_t projectee)
{
  return projectee;
}

uint32_t __proj__Mkstruct_four_byte_integer__item__four_byte_integer_value(uint32_t projectee)
{
  return projectee;
}

uint32_t
__proj__Mkstruct_variable_byte_integer__item__variable_byte_integer_value(uint32_t projectee)
{
  return projectee;
}

uint8_t
__proj__Mkstruct_property_error__item__property_error_code(struct_property_error projectee)
{
  return projectee.property_error_code;
}

C_String_t
__proj__Mkstruct_property_error__item__property_error_code_name(
  struct_property_error projectee
)
{
  return projectee.property_error_code_name;
}

uint8_t property_no_error_code = (uint8_t)0U;

uint8_t property_utf8_encoded_string_error_code = (uint8_t)1U;

uint8_t property_variable_integer_error_code = (uint8_t)2U;

uint8_t property_binary_data_error_code = (uint8_t)3U;

uint8_t property_utf8_encoded_string_pair_error_code = (uint8_t)4U;

uint8_t property_type_id_error_code = (uint8_t)5U;

struct_property_error define_struct_property_no_error;

struct_property_error define_struct_property_utf8_encoded_string_error;

struct_property_error define_struct_property_variable_integer_error;

struct_property_error define_struct_property_binary_data_error;

struct_property_error define_struct_property_utf8_encoded_string_pair_error;

struct_property_error define_struct_property_id_error;

uint8_t
__proj__Mkstruct_property_type__item__one_byte_integer_struct(struct_property_type projectee)
{
  return projectee.one_byte_integer_struct;
}

uint16_t
__proj__Mkstruct_property_type__item__two_byte_integer_struct(struct_property_type projectee)
{
  return projectee.two_byte_integer_struct;
}

uint32_t
__proj__Mkstruct_property_type__item__four_byte_integer_struct(struct_property_type projectee)
{
  return projectee.four_byte_integer_struct;
}

struct_utf8_string
__proj__Mkstruct_property_type__item__utf8_encoded_string_struct(
  struct_property_type projectee
)
{
  return projectee.utf8_encoded_string_struct;
}

uint32_t
__proj__Mkstruct_property_type__item__variable_byte_integer_struct(
  struct_property_type projectee
)
{
  return projectee.variable_byte_integer_struct;
}

struct_binary_data
__proj__Mkstruct_property_type__item__binary_data_struct(struct_property_type projectee)
{
  return projectee.binary_data_struct;
}

struct_utf8_string_pair
__proj__Mkstruct_property_type__item__utf8_string_pair_struct(struct_property_type projectee)
{
  return projectee.utf8_string_pair_struct;
}

struct_property_error
__proj__Mkstruct_property_type__item__property_type_error(struct_property_type projectee)
{
  return projectee.property_type_error;
}

uint8_t __proj__Mkstruct_property__item__property_id(struct_property projectee)
{
  return projectee.property_id;
}

uint8_t __proj__Mkstruct_property__item__property_type_id(struct_property projectee)
{
  return projectee.property_type_id;
}

struct_property_type
__proj__Mkstruct_property__item__property_type_struct(struct_property projectee)
{
  return projectee.property_type_struct;
}

uint32_t __proj__Mkstruct_property__item__payload_start_index(struct_property projectee)
{
  return projectee.payload_start_index;
}

bool __proj__Mkstruct_payload__item__is_valid_payload(struct_payload projectee)
{
  return projectee.is_valid_payload;
}

uint8_t *__proj__Mkstruct_payload__item__payload_value(struct_payload projectee)
{
  return projectee.payload_value;
}

uint32_t __proj__Mkstruct_payload__item__payload_length(struct_payload projectee)
{
  return projectee.payload_length;
}

uint32_t
__proj__Mkstruct_variable_header_publish__item__topic_length(
  struct_variable_header_publish projectee
)
{
  return projectee.topic_length;
}

C_String_t
__proj__Mkstruct_variable_header_publish__item__topic_name(
  struct_variable_header_publish projectee
)
{
  return projectee.topic_name;
}

uint16_t
__proj__Mkstruct_variable_header_publish__item__packet_identifier(
  struct_variable_header_publish projectee
)
{
  return projectee.packet_identifier;
}

struct_payload
__proj__Mkstruct_variable_header_publish__item__payload(
  struct_variable_header_publish projectee
)
{
  return projectee.payload;
}

uint16_t *__proj__Mkstruct_array_u16__item__array_u16(struct_array_u16 projectee)
{
  return projectee.array_u16;
}

uint32_t __proj__Mkstruct_array_u16__item__array_length_u16(struct_array_u16 projectee)
{
  return projectee.array_length_u16;
}

struct_property_type property_struct_type_base;

struct_property_type no_property_struct_type_base;

struct_property property_struct_base;

struct_disconnect_reason
__proj__Mkstruct_disconnect__item__disconnect_reason(struct_disconnect_reason projectee)
{
  return projectee;
}

uint32_t
__proj__Mkstruct_publish_parts__item__publish_remaining_length(struct_publish_parts projectee)
{
  return projectee.publish_remaining_length;
}

uint8_t __proj__Mkstruct_publish_parts__item__publish_flag(struct_publish_parts projectee)
{
  return projectee.publish_flag;
}

uint8_t __proj__Mkstruct_publish_parts__item__publish_dup_flag(struct_publish_parts projectee)
{
  return projectee.publish_dup_flag;
}

uint8_t __proj__Mkstruct_publish_parts__item__publish_qos_flag(struct_publish_parts projectee)
{
  return projectee.publish_qos_flag;
}

uint8_t
__proj__Mkstruct_publish_parts__item__publish_retain_flag(struct_publish_parts projectee)
{
  return projectee.publish_retain_flag;
}

C_String_t
__proj__Mkstruct_publish_parts__item__publish_topic_name(struct_publish_parts projectee)
{
  return projectee.publish_topic_name;
}

uint32_t
__proj__Mkstruct_publish_parts__item__publish_topic_length(struct_publish_parts projectee)
{
  return projectee.publish_topic_length;
}

uint16_t
__proj__Mkstruct_publish_parts__item__publish_packet_identifier(struct_publish_parts projectee)
{
  return projectee.publish_packet_identifier;
}

struct_payload
__proj__Mkstruct_publish_parts__item__publish_payload(struct_publish_parts projectee)
{
  return projectee.publish_payload;
}

struct_property
__proj__Mkstruct_publish_parts__item__publish_property(struct_publish_parts projectee)
{
  return projectee.publish_property;
}

struct_property
__proj__Mkstruct_connect_will__item__connect_will_property(struct_connect_will projectee)
{
  return projectee.connect_will_property;
}

struct_utf8_string
__proj__Mkstruct_connect_will__item__connect_will_topic_name(struct_connect_will projectee)
{
  return projectee.connect_will_topic_name;
}

struct_binary_data
__proj__Mkstruct_connect_will__item__connect_will_payload(struct_connect_will projectee)
{
  return projectee.connect_will_payload;
}

uint32_t
__proj__Mkstruct_connect_will__item__user_name_or_password_next_start_index(
  struct_connect_will projectee
)
{
  return projectee.user_name_or_password_next_start_index;
}

C_String_t __proj__Mkstruct_connect__item__protocol_name(struct_connect projectee)
{
  return projectee.protocol_name;
}

uint8_t __proj__Mkstruct_connect__item__protocol_version(struct_connect projectee)
{
  return projectee.protocol_version;
}

struct_connect_flags __proj__Mkstruct_connect__item__flags(struct_connect projectee)
{
  return projectee.flags;
}

uint16_t __proj__Mkstruct_connect__item__keep_alive(struct_connect projectee)
{
  return projectee.keep_alive;
}

struct_utf8_string __proj__Mkstruct_connect__item__connect_id(struct_connect projectee)
{
  return projectee.connect_id;
}

struct_connect_will __proj__Mkstruct_connect__item__will(struct_connect projectee)
{
  return projectee.will;
}

struct_utf8_string __proj__Mkstruct_connect__item__user_name(struct_connect projectee)
{
  return projectee.user_name;
}

struct_binary_data __proj__Mkstruct_connect__item__password(struct_connect projectee)
{
  return projectee.password;
}

uint8_t __proj__Mkstruct_fixed_header__item__message_type(struct_fixed_header projectee)
{
  return projectee.message_type;
}

C_String_t __proj__Mkstruct_fixed_header__item__message_name(struct_fixed_header projectee)
{
  return projectee.message_name;
}

struct_flags __proj__Mkstruct_fixed_header__item__flags(struct_fixed_header projectee)
{
  return projectee.flags;
}

uint32_t __proj__Mkstruct_fixed_header__item__remaining_length(struct_fixed_header projectee)
{
  return projectee.remaining_length;
}

struct_connect __proj__Mkstruct_fixed_header__item__connect(struct_fixed_header projectee)
{
  return projectee.connect;
}

struct_variable_header_publish
__proj__Mkstruct_fixed_header__item__publish(struct_fixed_header projectee)
{
  return projectee.publish;
}

struct_disconnect_reason
__proj__Mkstruct_fixed_header__item__disconnect(struct_fixed_header projectee)
{
  return projectee.disconnect;
}

struct_property __proj__Mkstruct_fixed_header__item__property(struct_fixed_header projectee)
{
  return projectee.property;
}

struct_error_struct __proj__Mkstruct_fixed_header__item__error(struct_fixed_header projectee)
{
  return projectee.error;
}

uint32_t
__proj__Mkstruct_connect_parts__item__connect_remaining_length(struct_connect_parts projectee)
{
  return projectee.connect_remaining_length;
}

struct_fixed_header_constant
__proj__Mkstruct_connect_parts__item__connect_connect_constant(struct_connect_parts projectee)
{
  return projectee.connect_connect_constant;
}

struct_connect
__proj__Mkstruct_connect_parts__item__connect_struct(struct_connect_parts projectee)
{
  return projectee.connect_struct;
}

struct_property
__proj__Mkstruct_connect_parts__item__connect_property(struct_connect_parts projectee)
{
  return projectee.connect_property;
}

uint32_t
__proj__Mkstruct_disconnect_parts__item__disconnect_remaining_length(
  struct_disconnect_parts projectee
)
{
  return projectee.disconnect_remaining_length;
}

struct_fixed_header_constant
__proj__Mkstruct_disconnect_parts__item__disconnect_disconnect_constant(
  struct_disconnect_parts projectee
)
{
  return projectee.disconnect_disconnect_constant;
}

struct_disconnect_reason
__proj__Mkstruct_disconnect_parts__item__disconnect_struct(struct_disconnect_parts projectee)
{
  return projectee.disconnect_struct;
}

struct_property
__proj__Mkstruct_disconnect_parts__item__property(struct_disconnect_parts projectee)
{
  return projectee.property;
}

bool __proj__Mkstruct_variable_length__item__have_error(struct_variable_length projectee)
{
  return projectee.have_error;
}

uint32_t
__proj__Mkstruct_variable_length__item__variable_length_value(struct_variable_length projectee)
{
  return projectee.variable_length_value;
}

uint32_t
__proj__Mkstruct_variable_length__item__next_start_index(struct_variable_length projectee)
{
  return projectee.next_start_index;
}

uint8_t
*__proj__Mkstruct_share_common_data__item__common_packet_data(
  struct_share_common_data projectee
)
{
  return projectee.common_packet_data;
}

uint32_t
__proj__Mkstruct_share_common_data__item__common_packet_size(
  struct_share_common_data projectee
)
{
  return projectee.common_packet_size;
}

uint8_t
__proj__Mkstruct_share_common_data__item__common_message_type(
  struct_share_common_data projectee
)
{
  return projectee.common_message_type;
}

uint8_t
__proj__Mkstruct_share_common_data__item__common_flag(struct_share_common_data projectee)
{
  return projectee.common_flag;
}

uint32_t
__proj__Mkstruct_share_common_data__item__common_remaining_length(
  struct_share_common_data projectee
)
{
  return projectee.common_remaining_length;
}

uint32_t
__proj__Mkstruct_share_common_data__item__common_next_start_index(
  struct_share_common_data projectee
)
{
  return projectee.common_next_start_index;
}

bool
__proj__Mkstruct_share_common_data_check__item__share_common_data_have_error(
  struct_share_common_data_check projectee
)
{
  return projectee.share_common_data_have_error;
}

struct_fixed_header
__proj__Mkstruct_share_common_data_check__item__share_common_data_error(
  struct_share_common_data_check projectee
)
{
  return projectee.share_common_data_error;
}

struct_share_common_data
__proj__Mkstruct_share_common_data_check__item__share_common_data(
  struct_share_common_data_check projectee
)
{
  return projectee.share_common_data;
}

uint8_t
__proj__Mkstruct_publish_packet_seed__item__publish_seed_dup_flag(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_dup_flag;
}

uint8_t
__proj__Mkstruct_publish_packet_seed__item__publish_seed_qos_flag(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_qos_flag;
}

uint8_t
__proj__Mkstruct_publish_packet_seed__item__publish_seed_retain_flag(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_retain_flag;
}

uint32_t
__proj__Mkstruct_publish_packet_seed__item__publish_seed_topic_length(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_topic_length;
}

C_String_t
__proj__Mkstruct_publish_packet_seed__item__publish_seed_topic_name(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_topic_name;
}

uint8_t
__proj__Mkstruct_publish_packet_seed__item__publish_seed_topic_name_error_status(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_topic_name_error_status;
}

uint16_t
__proj__Mkstruct_publish_packet_seed__item__publish_seed_packet_identifier(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_packet_identifier;
}

bool
__proj__Mkstruct_publish_packet_seed__item__publish_seed_is_searching_property_length(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_is_searching_property_length;
}

struct_payload
__proj__Mkstruct_publish_packet_seed__item__publish_seed_payload(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_payload;
}

uint8_t
__proj__Mkstruct_publish_packet_seed__item__publish_seed_payload_error_status(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_payload_error_status;
}

struct_property
__proj__Mkstruct_publish_packet_seed__item__publish_seed_property(
  struct_publish_packet_seed projectee
)
{
  return projectee.publish_seed_property;
}

bool
__proj__Mkstruct_connect_packet_seed__item__connect_seed_is_valid_protocol_name(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_is_valid_protocol_name;
}

bool
__proj__Mkstruct_connect_packet_seed__item__connect_seed_is_valid_protocol_version(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_is_valid_protocol_version;
}

uint8_t
__proj__Mkstruct_connect_packet_seed__item__connect_seed_connect_flag(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_connect_flag;
}

bool
__proj__Mkstruct_connect_packet_seed__item__connect_seed_is_valid_keep_alive(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_is_valid_keep_alive;
}

uint16_t
__proj__Mkstruct_connect_packet_seed__item__connect_seed_keep_alive(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_keep_alive;
}

bool
__proj__Mkstruct_connect_packet_seed__item__connect_seed_is_valid_property_length(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_is_valid_property_length;
}

struct_property
__proj__Mkstruct_connect_packet_seed__item__connect_seed_property(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_property;
}

struct_utf8_string
__proj__Mkstruct_connect_packet_seed__item__connect_seed_connect_id(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_connect_id;
}

struct_connect_will
__proj__Mkstruct_connect_packet_seed__item__connect_seed_will_struct(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_will_struct;
}

struct_utf8_string
__proj__Mkstruct_connect_packet_seed__item__connect_seed_user_name_struct(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_user_name_struct;
}

struct_binary_data
__proj__Mkstruct_connect_packet_seed__item__connect_seed_password_struct(
  struct_connect_packet_seed projectee
)
{
  return projectee.connect_seed_password_struct;
}

uint8_t
*__proj__Mkstruct_replace_utf8_encoded__item__replace_bom(
  struct_replace_utf8_encoded projectee
)
{
  return projectee.replace_bom;
}

uint32_t
__proj__Mkstruct_replace_utf8_encoded__item__bom_count(struct_replace_utf8_encoded projectee)
{
  return projectee.bom_count;
}

uint8_t __proj__Mkstruct_topic_name__item__topic_name_error_status(struct_topic_name projectee)
{
  return projectee.topic_name_error_status;
}

C_String_t __proj__Mkstruct_topic_name__item__topic_name(struct_topic_name projectee)
{
  return projectee.topic_name;
}

bool
__proj__Mkstruct_protocol_name__item__is_valid_protocol_name(struct_protocol_name projectee)
{
  return projectee.is_valid_protocol_name;
}

uint32_t
__proj__Mkstruct_protocol_name__item__protocol_version_start_index(
  struct_protocol_name projectee
)
{
  return projectee.protocol_version_start_index;
}

bool
__proj__Mkstruct_protocol_version__item__is_valid_protocol_version(
  struct_protocol_version projectee
)
{
  return projectee.is_valid_protocol_version;
}

uint32_t
__proj__Mkstruct_protocol_version__item__connect_flag_start_index(
  struct_protocol_version projectee
)
{
  return projectee.connect_flag_start_index;
}

uint8_t __proj__Mkstruct_connect_flag__item__connect_flag_value(struct_connect_flag projectee)
{
  return projectee.connect_flag_value;
}

uint32_t
__proj__Mkstruct_connect_flag__item__keep_alive_start_index(struct_connect_flag projectee)
{
  return projectee.keep_alive_start_index;
}

struct_disconnect_reason
__proj__Mkstruct_disconnect_packet_seed__item__disconnect_seed_reason(
  struct_disconnect_packet_seed projectee
)
{
  return projectee.disconnect_seed_reason;
}

struct_property
__proj__Mkstruct_disconnect_packet_seed__item__disconnect_seed_property(
  struct_disconnect_packet_seed projectee
)
{
  return projectee.disconnect_seed_property;
}

uint16_t
__proj__Mkstruct_packet_identifier__item__packet_identifier_value(
  struct_packet_identifier projectee
)
{
  return projectee.packet_identifier_value;
}

uint32_t
__proj__Mkstruct_packet_identifier__item__property_start_to_offset(
  struct_packet_identifier projectee
)
{
  return projectee.property_start_to_offset;
}

uint16_t __proj__Mkstruct_keep_alive__item__keep_alive_value(struct_keep_alive projectee)
{
  return projectee.keep_alive_value;
}

bool __proj__Mkstruct_keep_alive__item__is_valid_keep_alive(struct_keep_alive projectee)
{
  return projectee.is_valid_keep_alive;
}

bool
__proj__Mkstruct_is_valid_utf8_ready__item__ready_is_malformed_utf8(
  struct_is_valid_utf8_ready projectee
)
{
  return projectee.ready_is_malformed_utf8;
}

uint8_t
__proj__Mkstruct_is_valid_utf8_ready__item__ready_codelen(struct_is_valid_utf8_ready projectee)
{
  return projectee.ready_codelen;
}

uint16_t
__proj__Mkstruct_is_valid_utf8_ready__item__ready_codepoint(
  struct_is_valid_utf8_ready projectee
)
{
  return projectee.ready_codepoint;
}

struct_connect_will
__proj__Mkstruct_ready_connect_will__item__ready_connect_will_struct(
  struct_ready_connect_will projectee
)
{
  return projectee.ready_connect_will_struct;
}

bool
__proj__Mkstruct_ready_connect_will__item__ready_exsist_will(
  struct_ready_connect_will projectee
)
{
  return projectee.ready_exsist_will;
}

struct_utf8_string
__proj__Mkstruct_ready_connect_user_name__item__ready_connect_user_name_struct(
  struct_ready_connect_user_name projectee
)
{
  return projectee.ready_connect_user_name_struct;
}

bool
__proj__Mkstruct_ready_connect_user_name__item__ready_exsist_user_name(
  struct_ready_connect_user_name projectee
)
{
  return projectee.ready_exsist_user_name;
}

struct_binary_data
__proj__Mkstruct_ready_connect_password__item__ready_connect_password_struct(
  struct_ready_connect_password projectee
)
{
  return projectee.ready_connect_password_struct;
}

bool
__proj__Mkstruct_ready_connect_password__item__ready_exsist_password(
  struct_ready_connect_password projectee
)
{
  return projectee.ready_exsist_password;
}

