/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verbose -warn-error +9 -drop WasmSupport -drop C_Endianness -drop C -tmpdir ../out -fsopt --cache_dir -fsopt ../out -no-prefix Main -no-prefix Utils -no-prefix Const -no-prefix Common -no-prefix Publish -no-prefix Connect -no-prefix Disconnect -no-prefix FFI -no-prefix Debug -no-prefix Debug_FFI -o ../mqttPacketParser.out main.fst common.fst const.fst publish.fst connect.fst disconnect.fst ffi.fst debug.fst debug_ffi.fst ffi.c debug_ffi.c callMain.c
  F* version: ad3db6d3
  KreMLin version: 2f843633
 */

#include "kremlinit.h"


#if defined(__GNUC__) && !(defined(_WIN32) || defined(_WIN64))
__attribute__ ((visibility ("hidden")))
#endif


void kremlinit_globals()
{
  define_struct_connect_property_session_expiry_interval =
    (
      (struct_connect_property){
        .connect_property_id = define_connect_property_session_expiry_interval_id,
        .connect_property_name = "Session Expiry Interval"
      }
    );
  define_struct_connect_property_receive_maximum =
    (
      (struct_connect_property){
        .connect_property_id = define_connect_property_receive_maximum_id,
        .connect_property_name = "Receive Maximum"
      }
    );
  define_struct_connect_property_maximum_packet_size =
    (
      (struct_connect_property){
        .connect_property_id = define_connect_property_maximum_packet_size_id,
        .connect_property_name = "Maximum Packet Size"
      }
    );
  define_struct_connect_property_topic_alias_maximum =
    (
      (struct_connect_property){
        .connect_property_id = define_connect_property_topic_alias_maximum_id,
        .connect_property_name = "Topic Alias Maximum"
      }
    );
  define_struct_connect_property_request_response_information =
    (
      (struct_connect_property){
        .connect_property_id = define_connect_property_request_response_information_id,
        .connect_property_name = "Request Response Information"
      }
    );
  define_struct_connect_property_request_problem_information =
    (
      (struct_connect_property){
        .connect_property_id = define_connect_property_request_problem_information_id,
        .connect_property_name = "Request Problem Information"
      }
    );
  define_struct_connect_property_user_property =
    (
      (struct_connect_property){
        .connect_property_id = define_connect_property_user_property_id,
        .connect_property_name = "User Property"
      }
    );
  define_struct_connect_property_authentication_method =
    (
      (struct_connect_property){
        .connect_property_id = define_connect_property_authentication_method_id,
        .connect_property_name = "Authentication Method"
      }
    );
  define_struct_connect_property_authentication_data =
    (
      (struct_connect_property){
        .connect_property_id = define_connect_property_authentication_data_id,
        .connect_property_name = "Authentication Data"
      }
    );
  define_struct_disconnect_normal_disconnection =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_normal_disconnection,
        .disconnect_reason_code_name = define_disconnect_reason_code_normal_disconnection_name
      }
    );
  define_struct_disconnect_disconnect_with_will_message =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_disconnect_with_will_message,
        .disconnect_reason_code_name = define_disconnect_reason_code_disconnect_with_will_message_name
      }
    );
  define_struct_disconnect_unspecified_error =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_unspecified_error,
        .disconnect_reason_code_name = define_disconnect_reason_code_unspecified_error_name
      }
    );
  define_struct_disconnect_malformed_packet =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_malformed_packet,
        .disconnect_reason_code_name = define_disconnect_reason_code_malformed_packet_name
      }
    );
  define_struct_disconnect_protocol_error =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_protocol_error,
        .disconnect_reason_code_name = define_disconnect_reason_code_protocol_error_name
      }
    );
  define_struct_disconnect_implementation_specific_error =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_implementation_specific_error,
        .disconnect_reason_code_name = define_disconnect_reason_code_implementation_specific_error_name
      }
    );
  define_struct_disconnect_not_authorized =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_not_authorized,
        .disconnect_reason_code_name = define_disconnect_reason_code_not_authorized_name
      }
    );
  define_struct_disconnect_server_busy =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_server_busy,
        .disconnect_reason_code_name = define_disconnect_reason_code_server_busy_name
      }
    );
  define_struct_disconnect_server_shutting_down =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_server_shutting_down,
        .disconnect_reason_code_name = define_disconnect_reason_code_server_shutting_down_name
      }
    );
  define_struct_disconnect_keep_alive_timeout =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_keep_alive_timeout,
        .disconnect_reason_code_name = define_disconnect_reason_code_keep_alive_timeout_name
      }
    );
  define_struct_disconnect_session_taken_over =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_session_taken_over,
        .disconnect_reason_code_name = define_disconnect_reason_code_session_taken_over_name
      }
    );
  define_struct_disconnect_topic_filter_invalid =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_topic_filter_invalid,
        .disconnect_reason_code_name = define_disconnect_reason_code_topic_filter_invalid_name
      }
    );
  define_struct_disconnect_topic_name_invalid =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_code_topic_name_invalid,
        .disconnect_reason_code_name = define_disconnect_reason_code_topic_name_invalid_name
      }
    );
  define_struct_disconnect_receive_maximum_exceeded =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_receive_maximum_exceeded,
        .disconnect_reason_code_name = define_disconnect_reason_receive_maximum_exceeded_name
      }
    );
  define_struct_disconnect_topic_alias_invalid =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_topic_alias_invalid,
        .disconnect_reason_code_name = define_disconnect_reason_topic_alias_invalid_name
      }
    );
  define_struct_disconnect_packet_too_large =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_packet_too_large,
        .disconnect_reason_code_name = define_disconnect_reason_packet_too_large_name
      }
    );
  define_struct_disconnect_message_rate_too_high =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_message_rate_too_high,
        .disconnect_reason_code_name = define_disconnect_reason_message_rate_too_high_name
      }
    );
  define_struct_disconnect_quota_exceeded =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_quota_exceeded,
        .disconnect_reason_code_name = define_disconnect_reason_quota_exceeded_name
      }
    );
  define_struct_disconnect_administrative_action =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_administrative_action,
        .disconnect_reason_code_name = define_disconnect_reason_administrative_action_name
      }
    );
  define_struct_disconnect_payload_format_invalid =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_payload_format_invalid,
        .disconnect_reason_code_name = define_disconnect_reason_payload_format_invalid_name
      }
    );
  define_struct_disconnect_retain_not_supported =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_retain_not_supported,
        .disconnect_reason_code_name = define_disconnect_reason_retain_not_supported_name
      }
    );
  define_struct_disconnect_qos_not_supported =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_qos_not_supported,
        .disconnect_reason_code_name = define_disconnect_reason_qos_not_supported_name
      }
    );
  define_struct_disconnect_use_another_server =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_use_another_server,
        .disconnect_reason_code_name = define_disconnect_reason_use_another_server_name
      }
    );
  define_struct_disconnect_server_moved =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_server_moved,
        .disconnect_reason_code_name = define_disconnect_reason_server_moved_name
      }
    );
  define_struct_disconnect_shared_subscriptions_not_supported =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_shared_subscriptions_not_supported,
        .disconnect_reason_code_name = define_disconnect_reason_shared_subscriptions_not_supported_name
      }
    );
  define_struct_disconnect_connection_rate_exceeded =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_connection_rate_exceeded,
        .disconnect_reason_code_name = define_disconnect_reason_connection_rate_exceeded_name
      }
    );
  define_struct_disconnect_maximum_connect_time =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_maximum_connect_time,
        .disconnect_reason_code_name = define_disconnect_reason_maximum_connect_time_name
      }
    );
  define_struct_disconnect_subscription_identifiers_not_supported =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_subscription_identifiers_not_supported,
        .disconnect_reason_code_name = define_disconnect_reason_subscription_identifiers_not_supported_name
      }
    );
  define_struct_disconnect_wildcard_subscriptions_not_supported =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = define_disconnect_reason_wildcard_subscriptions_not_supported,
        .disconnect_reason_code_name = define_disconnect_reason_wildcard_subscriptions_not_supported_name
      }
    );
  define_struct_disconnect_error =
    (
      (struct_disconnect_reason){
        .disconnect_reason_code = max_u8,
        .disconnect_reason_code_name = ""
      }
    );
  define_struct_property_no_error =
    (
      (struct_property_error){
        .property_error_code = property_no_error_code,
        .property_error_code_name = ""
      }
    );
  define_struct_property_utf8_encoded_string_error =
    (
      (struct_property_error){
        .property_error_code = property_utf8_encoded_string_error_code,
        .property_error_code_name = "a utf8 encoded string property is invalid"
      }
    );
  define_struct_property_variable_integer_error =
    (
      (struct_property_error){
        .property_error_code = property_variable_integer_error_code,
        .property_error_code_name = "a variable integer property is invalid"
      }
    );
  define_struct_property_binary_data_error =
    (
      (struct_property_error){
        .property_error_code = property_binary_data_error_code,
        .property_error_code_name = "a binary data property is invalid"
      }
    );
  define_struct_property_utf8_encoded_string_pair_error =
    (
      (struct_property_error){
        .property_error_code = property_utf8_encoded_string_pair_error_code,
        .property_error_code_name = "a utf8 encoded string pair property is invalid"
      }
    );
  define_struct_property_id_error =
    (
      (struct_property_error){
        .property_error_code = property_type_id_error_code,
        .property_error_code_name = "property id is invalid"
      }
    );
  uint8_t empty_buffer = (uint8_t)0U;
  property_struct_type_base =
    (
      (struct_property_type){
        .one_byte_integer_struct = (uint8_t)0U,
        .two_byte_integer_struct = (uint16_t)0U,
        .four_byte_integer_struct = (uint32_t)0U,
        .utf8_encoded_string_struct = {
          .utf8_string_length = (uint16_t)0U,
          .utf8_string_value = &empty_buffer,
          .utf8_string_status_code = (uint8_t)0U,
          .utf8_next_start_index = (uint32_t)0U
        },
        .variable_byte_integer_struct = (uint32_t)0U,
        .binary_data_struct = {
          .is_valid_binary_data = false,
          .binary_length = (uint16_t)0U,
          .binary_value = &empty_buffer,
          .binary_next_start_index = (uint32_t)0U
        },
        .utf8_string_pair_struct = {
          .utf8_string_pair_key = {
            .utf8_string_length = (uint16_t)0U,
            .utf8_string_value = &empty_buffer,
            .utf8_string_status_code = (uint8_t)0U,
            .utf8_next_start_index = (uint32_t)0U
          },
          .utf8_string_pair_value = {
            .utf8_string_length = (uint16_t)0U,
            .utf8_string_value = &empty_buffer,
            .utf8_string_status_code = (uint8_t)0U,
            .utf8_next_start_index = (uint32_t)0U
          }
        },
        .property_type_error = define_struct_property_id_error
      }
    );
  uint8_t empty_buffer0 = (uint8_t)0U;
  no_property_struct_type_base =
    (
      (struct_property_type){
        .one_byte_integer_struct = (uint8_t)0U,
        .two_byte_integer_struct = (uint16_t)0U,
        .four_byte_integer_struct = (uint32_t)0U,
        .utf8_encoded_string_struct = {
          .utf8_string_length = (uint16_t)0U,
          .utf8_string_value = &empty_buffer0,
          .utf8_string_status_code = (uint8_t)0U,
          .utf8_next_start_index = (uint32_t)0U
        },
        .variable_byte_integer_struct = (uint32_t)0U,
        .binary_data_struct = {
          .is_valid_binary_data = false,
          .binary_length = (uint16_t)0U,
          .binary_value = &empty_buffer0,
          .binary_next_start_index = (uint32_t)0U
        },
        .utf8_string_pair_struct = {
          .utf8_string_pair_key = {
            .utf8_string_length = (uint16_t)0U,
            .utf8_string_value = &empty_buffer0,
            .utf8_string_status_code = (uint8_t)0U,
            .utf8_next_start_index = (uint32_t)0U
          },
          .utf8_string_pair_value = {
            .utf8_string_length = (uint16_t)0U,
            .utf8_string_value = &empty_buffer0,
            .utf8_string_status_code = (uint8_t)0U,
            .utf8_next_start_index = (uint32_t)0U
          }
        },
        .property_type_error = define_struct_property_no_error
      }
    );
  property_struct_base =
    (
      (struct_property){
        .property_id = max_u8,
        .property_type_id = max_u8,
        .property_type_struct = property_struct_type_base,
        .payload_start_index = (uint32_t)0U
      }
    );
}

