/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verbose -warn-error +9 -drop WasmSupport -drop C_Endianness -drop C -tmpdir ../out -fsopt --cache_dir -fsopt ../out -no-prefix Main -no-prefix Utils -no-prefix Const -no-prefix Common -no-prefix Publish -no-prefix Connect -no-prefix Disconnect -no-prefix FFI -no-prefix Debug -no-prefix Debug_FFI -o ../mqttPacketParser.out main.fst common.fst const.fst publish.fst connect.fst disconnect.fst ffi.fst debug.fst debug_ffi.fst ffi.c debug_ffi.c callMain.c
  F* version: ad3db6d3
  KreMLin version: 2f843633
 */

#include "Main.h"

struct_fixed_header mqtt_packet_parse(uint8_t *packet_data, uint32_t packet_size)
{
  struct_share_common_data_check
  share_common_data_check1 = share_common_data_check(packet_data, packet_size);
  if (share_common_data_check1.share_common_data_have_error)
    return share_common_data_check1.share_common_data_error;
  else
  {
    struct_share_common_data share_common_data = share_common_data_check1.share_common_data;
    if
    (
      share_common_data.common_message_type
      == define_mqtt_control_packet_PUBLISH
      && share_common_data.common_packet_size >= (uint32_t)3U
      &&
        share_common_data.common_next_start_index
        < share_common_data.common_packet_size - (uint32_t)3U
    )
      return publish_packet_parse_result(share_common_data);
    else if
    (
      share_common_data.common_message_type
      == define_mqtt_control_packet_CONNECT
      && share_common_data.common_packet_size >= (uint32_t)6U
      &&
        share_common_data.common_next_start_index
        < share_common_data.common_packet_size - (uint32_t)6U
    )
      return connect_packet_parse_result(share_common_data);
    else if
    (
      share_common_data.common_message_type
      == define_mqtt_control_packet_DISCONNECT
      && share_common_data.common_next_start_index < share_common_data.common_packet_size
    )
      return disconnect_packet_parse_result(share_common_data);
    else
    {
      struct_error_struct
      error_struct =
        {
          .code = define_error_message_type_invalid_code,
          .message = define_error_message_type_invalid
        };
      unimplemented("Unknown Packet type.\n");
      return error_struct_fixed_header(error_struct);
    }
  }
}

