/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verbose -warn-error +9 -drop WasmSupport -drop C_Endianness -drop C -tmpdir ../out -fsopt --cache_dir -fsopt ../out -no-prefix Main -no-prefix Utils -no-prefix Const -no-prefix Common -no-prefix Publish -no-prefix Connect -no-prefix Disconnect -no-prefix FFI -no-prefix Debug -no-prefix Debug_FFI -o ../mqttPacketParser.out main.fst common.fst const.fst publish.fst connect.fst disconnect.fst ffi.fst debug.fst debug_ffi.fst ffi.c debug_ffi.c callMain.c
  F* version: ad3db6d3
  KreMLin version: 2f843633
 */

#include "kremlib.h"
#ifndef __Publish_H
#define __Publish_H

#include "Const.h"
#include "Common.h"
#include "FFI.h"


struct_fixed_header_constant
struct_fixed_publish(uint8_t flag, uint8_t dup_flag, uint8_t qos_flag, uint8_t retain_flag);

struct_fixed_header assemble_publish_struct(struct_publish_parts s);

struct_topic_name
get_topic_name(
  uint8_t *packet_data,
  uint32_t packet_size,
  uint32_t topic_name_start_index,
  uint32_t topic_length
);

struct_publish_packet_seed
publish_packet_parser(
  uint8_t *packet_data,
  uint32_t packet_size,
  uint8_t common_flag,
  uint32_t next_start_index
);

struct_fixed_header publish_packet_parse_result(struct_share_common_data share_common_data);

#define __Publish_H_DEFINED
#endif
